version: "3"

services:
  deployer-test:
    container_name: deployer-test
      build:
        context: ./
        dockerfile: Dockerfile
        args:
          DEPLOY_ENV: ".env"
    image: deployer-test
    restart: always
    network_mode: bridge
    ports:
      - "5050:5050"